version: "3"
services:
  backend:
    build:
      context: ./bpme-backend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
  frontend:
    build:
      context: ./bpme-frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./bpme-frontend:/usr/app
      - /usr/app/node_modules
    ports:
      # not sure about this
      - "5173:5173"
    depends_on:
      - backend
