version: "3"
services:
  backend:
    build: ./bpme-backend
    ports:
      - "8080:8080"
    volumes:
    - /bpme-backend:/app
    depends_on:
      - frontend
  frontend:
    build: ./bpme-frontend
    ports:
      - "5173:5173"
    volumes:
      - /bpme-frontend:/app
