FROM eclipse-temurin:17-alpine
WORKDIR /usr/app

COPY . .

RUN apk update && apk add maven && apk add openjdk17-jre-headless
RUN mvn clean install
RUN ls -l target
RUN chmod +x target/bpme-0.0.1-SNAPSHOT.jar
CMD ["java", "-jar", "target/bpme-0.0.1-SNAPSHOT.jar"]
EXPOSE 8080